//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Antlr4Source\UserAgent.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OrbintSoft.Yauaa.Antlr4Source {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="UserAgentParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IUserAgentListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.userAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUserAgent([NotNull] UserAgentParser.UserAgentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.userAgent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUserAgent([NotNull] UserAgentParser.UserAgentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.rootElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRootElements([NotNull] UserAgentParser.RootElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.rootElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRootElements([NotNull] UserAgentParser.RootElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.rootText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRootText([NotNull] UserAgentParser.RootTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.rootText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRootText([NotNull] UserAgentParser.RootTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.product"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduct([NotNull] UserAgentParser.ProductContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.product"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduct([NotNull] UserAgentParser.ProductContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentProduct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentProduct([NotNull] UserAgentParser.CommentProductContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentProduct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentProduct([NotNull] UserAgentParser.CommentProductContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersionWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductVersionWords([NotNull] UserAgentParser.ProductVersionWordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersionWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductVersionWords([NotNull] UserAgentParser.ProductVersionWordsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductName([NotNull] UserAgentParser.ProductNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductName([NotNull] UserAgentParser.ProductNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameWords([NotNull] UserAgentParser.ProductNameWordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameWords([NotNull] UserAgentParser.ProductNameWordsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductVersion([NotNull] UserAgentParser.ProductVersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductVersion([NotNull] UserAgentParser.ProductVersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersionWithCommas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductVersionWithCommas([NotNull] UserAgentParser.ProductVersionWithCommasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersionWithCommas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductVersionWithCommas([NotNull] UserAgentParser.ProductVersionWithCommasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersionSingleWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductVersionSingleWord([NotNull] UserAgentParser.ProductVersionSingleWordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersionSingleWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductVersionSingleWord([NotNull] UserAgentParser.ProductVersionSingleWordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.singleVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleVersion([NotNull] UserAgentParser.SingleVersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.singleVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleVersion([NotNull] UserAgentParser.SingleVersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.singleVersionWithCommas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleVersionWithCommas([NotNull] UserAgentParser.SingleVersionWithCommasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.singleVersionWithCommas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleVersionWithCommas([NotNull] UserAgentParser.SingleVersionWithCommasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameVersion([NotNull] UserAgentParser.ProductNameVersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameVersion([NotNull] UserAgentParser.ProductNameVersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameEmail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameEmail([NotNull] UserAgentParser.ProductNameEmailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameEmail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameEmail([NotNull] UserAgentParser.ProductNameEmailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameUrl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameUrl([NotNull] UserAgentParser.ProductNameUrlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameUrl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameUrl([NotNull] UserAgentParser.ProductNameUrlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameUuid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameUuid([NotNull] UserAgentParser.ProductNameUuidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameUuid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameUuid([NotNull] UserAgentParser.ProductNameUuidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.uuId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUuId([NotNull] UserAgentParser.UuIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.uuId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUuId([NotNull] UserAgentParser.UuIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.emailAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmailAddress([NotNull] UserAgentParser.EmailAddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.emailAddress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmailAddress([NotNull] UserAgentParser.EmailAddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.siteUrl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSiteUrl([NotNull] UserAgentParser.SiteUrlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.siteUrl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSiteUrl([NotNull] UserAgentParser.SiteUrlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.base64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase64([NotNull] UserAgentParser.Base64Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.base64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase64([NotNull] UserAgentParser.Base64Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentSeparator([NotNull] UserAgentParser.CommentSeparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentSeparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentSeparator([NotNull] UserAgentParser.CommentSeparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentBlock([NotNull] UserAgentParser.CommentBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentBlock([NotNull] UserAgentParser.CommentBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentEntry([NotNull] UserAgentParser.CommentEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentEntry([NotNull] UserAgentParser.CommentEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameKeyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameKeyValue([NotNull] UserAgentParser.ProductNameKeyValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameKeyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameKeyValue([NotNull] UserAgentParser.ProductNameKeyValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameNoVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductNameNoVersion([NotNull] UserAgentParser.ProductNameNoVersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameNoVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductNameNoVersion([NotNull] UserAgentParser.ProductNameNoVersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyValueProductVersionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValueProductVersionName([NotNull] UserAgentParser.KeyValueProductVersionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyValueProductVersionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValueProductVersionName([NotNull] UserAgentParser.KeyValueProductVersionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValue([NotNull] UserAgentParser.KeyValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValue([NotNull] UserAgentParser.KeyValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyWithoutValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyWithoutValue([NotNull] UserAgentParser.KeyWithoutValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyWithoutValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyWithoutValue([NotNull] UserAgentParser.KeyWithoutValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyValueVersionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValueVersionName([NotNull] UserAgentParser.KeyValueVersionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyValueVersionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValueVersionName([NotNull] UserAgentParser.KeyValueVersionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyName([NotNull] UserAgentParser.KeyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyName([NotNull] UserAgentParser.KeyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.emptyWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyWord([NotNull] UserAgentParser.EmptyWordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.emptyWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyWord([NotNull] UserAgentParser.EmptyWordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.multipleWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultipleWords([NotNull] UserAgentParser.MultipleWordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.multipleWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultipleWords([NotNull] UserAgentParser.MultipleWordsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.versionWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersionWords([NotNull] UserAgentParser.VersionWordsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.versionWords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersionWords([NotNull] UserAgentParser.VersionWordsContext context);
}
} // namespace OrbintSoft.Yauaa.Antlr4Source
