//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Antlr4Source\UserAgentTreeWalker.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OrbintSoft.Yauaa.Antlr4Source {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class UserAgentTreeWalkerLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, VALUENAME=9, 
		VALUE=10, UP=11, NEXT=12, NEXT2=13, NEXT3=14, NEXT4=15, PREV=16, PREV2=17, 
		PREV3=18, PREV4=19, DOT=20, MINUS=21, STAR=22, IN=23, NUMBER=24, BLOCKOPEN=25, 
		BLOCKCLOSE=26, BRACEOPEN=27, BRACECLOSE=28, DOUBLEQUOTE=29, COLON=30, 
		SEMICOLON=31, SPACE=32, NOTEQUALS=33, EQUALS=34, CONTAINS=35, STARTSWITH=36, 
		ENDSWITH=37, BACKTOFULL=38;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "VALUENAME", 
		"VALUE", "UP", "NEXT", "NEXT2", "NEXT3", "NEXT4", "PREV", "PREV2", "PREV3", 
		"PREV4", "DOT", "MINUS", "STAR", "IN", "NUMBER", "BLOCKOPEN", "BLOCKCLOSE", 
		"BRACEOPEN", "BRACECLOSE", "DOUBLEQUOTE", "COLON", "SEMICOLON", "SPACE", 
		"NOTEQUALS", "EQUALS", "CONTAINS", "STARTSWITH", "ENDSWITH", "BACKTOFULL"
	};


	public UserAgentTreeWalkerLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public UserAgentTreeWalkerLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'IsNull'", "'Concat'", "'NormalizeBrand'", "'CleanVersion'", "'LookUp'", 
		"'LookUpPrefix'", "'IsInLookUpPrefix'", "'agent'", null, null, "'^'", 
		"'>'", "'>>'", "'>>>'", "'>>>>'", "'<'", "'<<'", "'<<<'", "'<<<<'", "'.'", 
		"'-'", "'*'", "'?'", null, "'['", "']'", "'('", "')'", "'\"'", "':'", 
		"';'", null, "'!='", "'='", "'~'", "'{'", "'}'", "'@'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "VALUENAME", "VALUE", 
		"UP", "NEXT", "NEXT2", "NEXT3", "NEXT4", "PREV", "PREV2", "PREV3", "PREV4", 
		"DOT", "MINUS", "STAR", "IN", "NUMBER", "BLOCKOPEN", "BLOCKCLOSE", "BRACEOPEN", 
		"BRACECLOSE", "DOUBLEQUOTE", "COLON", "SEMICOLON", "SPACE", "NOTEQUALS", 
		"EQUALS", "CONTAINS", "STARTSWITH", "ENDSWITH", "BACKTOFULL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "UserAgentTreeWalker.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static UserAgentTreeWalkerLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '(', '\x102', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x6', '\n', '\xA7', '\n', '\n', '\r', '\n', '\xE', '\n', 
		'\xA8', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', 
		'\xAF', '\n', '\v', '\f', '\v', '\xE', '\v', '\xB2', '\v', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x6', '\x19', '\xDD', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xDE', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x6', 
		'!', '\xF0', '\n', '!', '\r', '!', '\xE', '!', '\xF1', '\x3', '!', '\x3', 
		'!', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'$', '\x3', '$', '\x3', '%', '\x3', '%', '\x3', '&', '\x3', '&', '\x3', 
		'\'', '\x3', '\'', '\x2', '\x2', '(', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 
		'G', '%', 'I', '&', 'K', '\'', 'M', '(', '\x3', '\x2', '\b', '\x4', '\x2', 
		'\x43', '\\', '\x63', '|', '\x5', '\x2', '\x32', ';', '\x43', '\\', '\x63', 
		'|', '\n', '\x2', '$', '$', ')', ')', '^', '^', '\x64', '\x64', 'h', 'h', 
		'p', 'p', 't', 't', 'v', 'v', '\x4', '\x2', '$', '$', '^', '^', '\x3', 
		'\x2', '\x32', ';', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', '\x106', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'I', '\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'M', '\x3', '\x2', '\x2', '\x2', '\x3', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\x5', 'V', '\x3', '\x2', '\x2', '\x2', '\a', ']', '\x3', 
		'\x2', '\x2', '\x2', '\t', 'l', '\x3', '\x2', '\x2', '\x2', '\v', 'y', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x11', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\xA4', '\x3', '\x2', '\x2', '\x2', '\x15', '\xAA', 
		'\x3', '\x2', '\x2', '\x2', '\x17', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '\xB7', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\xBC', '\x3', '\x2', '\x2', '\x2', '\x1F', '\xC0', 
		'\x3', '\x2', '\x2', '\x2', '!', '\xC5', '\x3', '\x2', '\x2', '\x2', '#', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '%', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\xCE', '\x3', '\x2', '\x2', '\x2', ')', '\xD3', '\x3', '\x2', 
		'\x2', '\x2', '+', '\xD5', '\x3', '\x2', '\x2', '\x2', '-', '\xD7', '\x3', 
		'\x2', '\x2', '\x2', '/', '\xD9', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\x33', '\xE0', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xE2', '\x3', '\x2', '\x2', '\x2', '\x37', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xE6', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '=', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '?', '\xEC', '\x3', '\x2', '\x2', '\x2', '\x41', '\xEF', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\xF5', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\xF8', '\x3', '\x2', '\x2', '\x2', 'G', '\xFA', '\x3', '\x2', '\x2', 
		'\x2', 'I', '\xFC', '\x3', '\x2', '\x2', '\x2', 'K', '\xFE', '\x3', '\x2', 
		'\x2', '\x2', 'M', '\x100', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', 
		'K', '\x2', '\x2', 'P', 'Q', '\a', 'u', '\x2', '\x2', 'Q', 'R', '\a', 
		'P', '\x2', '\x2', 'R', 'S', '\a', 'w', '\x2', '\x2', 'S', 'T', '\a', 
		'n', '\x2', '\x2', 'T', 'U', '\a', 'n', '\x2', '\x2', 'U', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'V', 'W', '\a', '\x45', '\x2', '\x2', 'W', 'X', '\a', 
		'q', '\x2', '\x2', 'X', 'Y', '\a', 'p', '\x2', '\x2', 'Y', 'Z', '\a', 
		'\x65', '\x2', '\x2', 'Z', '[', '\a', '\x63', '\x2', '\x2', '[', '\\', 
		'\a', 'v', '\x2', '\x2', '\\', '\x6', '\x3', '\x2', '\x2', '\x2', ']', 
		'^', '\a', 'P', '\x2', '\x2', '^', '_', '\a', 'q', '\x2', '\x2', '_', 
		'`', '\a', 't', '\x2', '\x2', '`', '\x61', '\a', 'o', '\x2', '\x2', '\x61', 
		'\x62', '\a', '\x63', '\x2', '\x2', '\x62', '\x63', '\a', 'n', '\x2', 
		'\x2', '\x63', '\x64', '\a', 'k', '\x2', '\x2', '\x64', '\x65', '\a', 
		'|', '\x2', '\x2', '\x65', '\x66', '\a', 'g', '\x2', '\x2', '\x66', 'g', 
		'\a', '\x44', '\x2', '\x2', 'g', 'h', '\a', 't', '\x2', '\x2', 'h', 'i', 
		'\a', '\x63', '\x2', '\x2', 'i', 'j', '\a', 'p', '\x2', '\x2', 'j', 'k', 
		'\a', '\x66', '\x2', '\x2', 'k', '\b', '\x3', '\x2', '\x2', '\x2', 'l', 
		'm', '\a', '\x45', '\x2', '\x2', 'm', 'n', '\a', 'n', '\x2', '\x2', 'n', 
		'o', '\a', 'g', '\x2', '\x2', 'o', 'p', '\a', '\x63', '\x2', '\x2', 'p', 
		'q', '\a', 'p', '\x2', '\x2', 'q', 'r', '\a', 'X', '\x2', '\x2', 'r', 
		's', '\a', 'g', '\x2', '\x2', 's', 't', '\a', 't', '\x2', '\x2', 't', 
		'u', '\a', 'u', '\x2', '\x2', 'u', 'v', '\a', 'k', '\x2', '\x2', 'v', 
		'w', '\a', 'q', '\x2', '\x2', 'w', 'x', '\a', 'p', '\x2', '\x2', 'x', 
		'\n', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', 'N', '\x2', '\x2', 'z', 
		'{', '\a', 'q', '\x2', '\x2', '{', '|', '\a', 'q', '\x2', '\x2', '|', 
		'}', '\a', 'm', '\x2', '\x2', '}', '~', '\a', 'W', '\x2', '\x2', '~', 
		'\x7F', '\a', 'r', '\x2', '\x2', '\x7F', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\x80', '\x81', '\a', 'N', '\x2', '\x2', '\x81', '\x82', '\a', 'q', '\x2', 
		'\x2', '\x82', '\x83', '\a', 'q', '\x2', '\x2', '\x83', '\x84', '\a', 
		'm', '\x2', '\x2', '\x84', '\x85', '\a', 'W', '\x2', '\x2', '\x85', '\x86', 
		'\a', 'r', '\x2', '\x2', '\x86', '\x87', '\a', 'R', '\x2', '\x2', '\x87', 
		'\x88', '\a', 't', '\x2', '\x2', '\x88', '\x89', '\a', 'g', '\x2', '\x2', 
		'\x89', '\x8A', '\a', 'h', '\x2', '\x2', '\x8A', '\x8B', '\a', 'k', '\x2', 
		'\x2', '\x8B', '\x8C', '\a', 'z', '\x2', '\x2', '\x8C', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', 'K', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', 'u', '\x2', '\x2', '\x8F', '\x90', '\a', 'K', '\x2', '\x2', 
		'\x90', '\x91', '\a', 'p', '\x2', '\x2', '\x91', '\x92', '\a', 'N', '\x2', 
		'\x2', '\x92', '\x93', '\a', 'q', '\x2', '\x2', '\x93', '\x94', '\a', 
		'q', '\x2', '\x2', '\x94', '\x95', '\a', 'm', '\x2', '\x2', '\x95', '\x96', 
		'\a', 'W', '\x2', '\x2', '\x96', '\x97', '\a', 'r', '\x2', '\x2', '\x97', 
		'\x98', '\a', 'R', '\x2', '\x2', '\x98', '\x99', '\a', 't', '\x2', '\x2', 
		'\x99', '\x9A', '\a', 'g', '\x2', '\x2', '\x9A', '\x9B', '\a', 'h', '\x2', 
		'\x2', '\x9B', '\x9C', '\a', 'k', '\x2', '\x2', '\x9C', '\x9D', '\a', 
		'z', '\x2', '\x2', '\x9D', '\x10', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x9F', '\a', '\x63', '\x2', '\x2', '\x9F', '\xA0', '\a', 'i', '\x2', 
		'\x2', '\xA0', '\xA1', '\a', 'g', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'p', '\x2', '\x2', '\xA2', '\xA3', '\a', 'v', '\x2', '\x2', '\xA3', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA6', '\t', '\x2', '\x2', '\x2', 
		'\xA5', '\xA7', '\t', '\x3', '\x2', '\x2', '\xA6', '\xA5', '\x3', '\x2', 
		'\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\x14', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xB0', '\x5', ';', 
		'\x1E', '\x2', '\xAB', '\xAC', '\a', '^', '\x2', '\x2', '\xAC', '\xAF', 
		'\t', '\x4', '\x2', '\x2', '\xAD', '\xAF', '\n', '\x5', '\x2', '\x2', 
		'\xAE', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAD', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB4', '\x5', ';', '\x1E', '\x2', '\xB4', '\x16', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', '`', '\x2', '\x2', '\xB6', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\a', '@', '\x2', 
		'\x2', '\xB8', '\x1A', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\a', 
		'@', '\x2', '\x2', '\xBA', '\xBB', '\a', '@', '\x2', '\x2', '\xBB', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\a', '@', '\x2', '\x2', '\xBD', 
		'\xBE', '\a', '@', '\x2', '\x2', '\xBE', '\xBF', '\a', '@', '\x2', '\x2', 
		'\xBF', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\a', '@', 
		'\x2', '\x2', '\xC1', '\xC2', '\a', '@', '\x2', '\x2', '\xC2', '\xC3', 
		'\a', '@', '\x2', '\x2', '\xC3', '\xC4', '\a', '@', '\x2', '\x2', '\xC4', 
		' ', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\a', '>', '\x2', '\x2', 
		'\xC6', '\"', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\a', '>', '\x2', 
		'\x2', '\xC8', '\xC9', '\a', '>', '\x2', '\x2', '\xC9', '$', '\x3', '\x2', 
		'\x2', '\x2', '\xCA', '\xCB', '\a', '>', '\x2', '\x2', '\xCB', '\xCC', 
		'\a', '>', '\x2', '\x2', '\xCC', '\xCD', '\a', '>', '\x2', '\x2', '\xCD', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', '\a', '>', '\x2', '\x2', 
		'\xCF', '\xD0', '\a', '>', '\x2', '\x2', '\xD0', '\xD1', '\a', '>', '\x2', 
		'\x2', '\xD1', '\xD2', '\a', '>', '\x2', '\x2', '\xD2', '(', '\x3', '\x2', 
		'\x2', '\x2', '\xD3', '\xD4', '\a', '\x30', '\x2', '\x2', '\xD4', '*', 
		'\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\a', '/', '\x2', '\x2', '\xD6', 
		',', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\a', ',', '\x2', '\x2', 
		'\xD8', '.', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\a', '\x41', 
		'\x2', '\x2', '\xDA', '\x30', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDD', 
		'\t', '\x6', '\x2', '\x2', '\xDC', '\xDB', '\x3', '\x2', '\x2', '\x2', 
		'\xDD', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDC', '\x3', '\x2', 
		'\x2', '\x2', '\xDE', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDF', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\a', ']', '\x2', '\x2', '\xE1', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE3', '\a', '_', '\x2', 
		'\x2', '\xE3', '\x36', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE5', '\a', 
		'*', '\x2', '\x2', '\xE5', '\x38', '\x3', '\x2', '\x2', '\x2', '\xE6', 
		'\xE7', '\a', '+', '\x2', '\x2', '\xE7', ':', '\x3', '\x2', '\x2', '\x2', 
		'\xE8', '\xE9', '\a', '$', '\x2', '\x2', '\xE9', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\xEB', '\a', '<', '\x2', '\x2', '\xEB', '>', '\x3', '\x2', 
		'\x2', '\x2', '\xEC', '\xED', '\a', '=', '\x2', '\x2', '\xED', '@', '\x3', 
		'\x2', '\x2', '\x2', '\xEE', '\xF0', '\t', '\a', '\x2', '\x2', '\xEF', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF1', '\x3', '\x2', '\x2', 
		'\x2', '\xF1', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\xF2', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF3', 
		'\xF4', '\b', '!', '\x2', '\x2', '\xF4', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\xF5', '\xF6', '\a', '#', '\x2', '\x2', '\xF6', '\xF7', '\a', 
		'?', '\x2', '\x2', '\xF7', '\x44', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\xF9', '\a', '?', '\x2', '\x2', '\xF9', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\xFA', '\xFB', '\a', '\x80', '\x2', '\x2', '\xFB', 'H', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\xFD', '\a', '}', '\x2', '\x2', '\xFD', 
		'J', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFF', '\a', '\x7F', '\x2', 
		'\x2', '\xFF', 'L', '\x3', '\x2', '\x2', '\x2', '\x100', '\x101', '\a', 
		'\x42', '\x2', '\x2', '\x101', 'N', '\x3', '\x2', '\x2', '\x2', '\b', 
		'\x2', '\xA8', '\xAE', '\xB0', '\xDE', '\xF1', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace OrbintSoft.Yauaa.Antlr4Source
