//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Antlr4Source\UserAgent.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OrbintSoft.Yauaa.Antlr4Source {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUserAgentListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class UserAgentBaseListener : IUserAgentListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.userAgent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUserAgent([NotNull] UserAgentParser.UserAgentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.userAgent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUserAgent([NotNull] UserAgentParser.UserAgentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.rootElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRootElements([NotNull] UserAgentParser.RootElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.rootElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRootElements([NotNull] UserAgentParser.RootElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.rootText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRootText([NotNull] UserAgentParser.RootTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.rootText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRootText([NotNull] UserAgentParser.RootTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.product"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProduct([NotNull] UserAgentParser.ProductContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.product"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProduct([NotNull] UserAgentParser.ProductContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentProduct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentProduct([NotNull] UserAgentParser.CommentProductContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentProduct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentProduct([NotNull] UserAgentParser.CommentProductContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersionWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductVersionWords([NotNull] UserAgentParser.ProductVersionWordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersionWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductVersionWords([NotNull] UserAgentParser.ProductVersionWordsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductName([NotNull] UserAgentParser.ProductNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductName([NotNull] UserAgentParser.ProductNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameWords([NotNull] UserAgentParser.ProductNameWordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameWords([NotNull] UserAgentParser.ProductNameWordsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductVersion([NotNull] UserAgentParser.ProductVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductVersion([NotNull] UserAgentParser.ProductVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersionWithCommas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductVersionWithCommas([NotNull] UserAgentParser.ProductVersionWithCommasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersionWithCommas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductVersionWithCommas([NotNull] UserAgentParser.ProductVersionWithCommasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productVersionSingleWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductVersionSingleWord([NotNull] UserAgentParser.ProductVersionSingleWordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productVersionSingleWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductVersionSingleWord([NotNull] UserAgentParser.ProductVersionSingleWordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.singleVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleVersion([NotNull] UserAgentParser.SingleVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.singleVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleVersion([NotNull] UserAgentParser.SingleVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.singleVersionWithCommas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleVersionWithCommas([NotNull] UserAgentParser.SingleVersionWithCommasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.singleVersionWithCommas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleVersionWithCommas([NotNull] UserAgentParser.SingleVersionWithCommasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameVersion([NotNull] UserAgentParser.ProductNameVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameVersion([NotNull] UserAgentParser.ProductNameVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameEmail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameEmail([NotNull] UserAgentParser.ProductNameEmailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameEmail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameEmail([NotNull] UserAgentParser.ProductNameEmailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameUrl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameUrl([NotNull] UserAgentParser.ProductNameUrlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameUrl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameUrl([NotNull] UserAgentParser.ProductNameUrlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameUuid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameUuid([NotNull] UserAgentParser.ProductNameUuidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameUuid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameUuid([NotNull] UserAgentParser.ProductNameUuidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.uuId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUuId([NotNull] UserAgentParser.UuIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.uuId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUuId([NotNull] UserAgentParser.UuIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.emailAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmailAddress([NotNull] UserAgentParser.EmailAddressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.emailAddress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmailAddress([NotNull] UserAgentParser.EmailAddressContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.siteUrl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSiteUrl([NotNull] UserAgentParser.SiteUrlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.siteUrl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSiteUrl([NotNull] UserAgentParser.SiteUrlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.base64"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase64([NotNull] UserAgentParser.Base64Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.base64"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase64([NotNull] UserAgentParser.Base64Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentSeparator([NotNull] UserAgentParser.CommentSeparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentSeparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentSeparator([NotNull] UserAgentParser.CommentSeparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentBlock([NotNull] UserAgentParser.CommentBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentBlock([NotNull] UserAgentParser.CommentBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.commentEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentEntry([NotNull] UserAgentParser.CommentEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.commentEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentEntry([NotNull] UserAgentParser.CommentEntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameKeyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameKeyValue([NotNull] UserAgentParser.ProductNameKeyValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameKeyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameKeyValue([NotNull] UserAgentParser.ProductNameKeyValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.productNameNoVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProductNameNoVersion([NotNull] UserAgentParser.ProductNameNoVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.productNameNoVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProductNameNoVersion([NotNull] UserAgentParser.ProductNameNoVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyValueProductVersionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValueProductVersionName([NotNull] UserAgentParser.KeyValueProductVersionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyValueProductVersionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValueProductVersionName([NotNull] UserAgentParser.KeyValueProductVersionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValue([NotNull] UserAgentParser.KeyValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValue([NotNull] UserAgentParser.KeyValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyWithoutValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyWithoutValue([NotNull] UserAgentParser.KeyWithoutValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyWithoutValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyWithoutValue([NotNull] UserAgentParser.KeyWithoutValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyValueVersionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValueVersionName([NotNull] UserAgentParser.KeyValueVersionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyValueVersionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValueVersionName([NotNull] UserAgentParser.KeyValueVersionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.keyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyName([NotNull] UserAgentParser.KeyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.keyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyName([NotNull] UserAgentParser.KeyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.emptyWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyWord([NotNull] UserAgentParser.EmptyWordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.emptyWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyWord([NotNull] UserAgentParser.EmptyWordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.multipleWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultipleWords([NotNull] UserAgentParser.MultipleWordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.multipleWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultipleWords([NotNull] UserAgentParser.MultipleWordsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UserAgentParser.versionWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVersionWords([NotNull] UserAgentParser.VersionWordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UserAgentParser.versionWords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVersionWords([NotNull] UserAgentParser.VersionWordsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace OrbintSoft.Yauaa.Antlr4Source
